AWSTemplateFormatVersion: "2010-09-09"
Description: "Base: VPC, Subnets, ECS Cluster y roles comunes"

Parameters:
  EnvironmentName:
    Type: String
    Default: "dev"

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-vpc"

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]

  # (Agrega más subnets si quieres alta disponibilidad)

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${EnvironmentName}-ecs"

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  DefaultServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "SG comun ECS services ${EnvironmentName}"
      VpcId: !Ref Vpc
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

Outputs:
  VpcId:
    Value: !Ref Vpc
    Export:
      Name: !Sub "${EnvironmentName}-VpcId"

  PublicSubnets:
    Value: !Join [",", [!Ref PublicSubnetA]]
    Export:
      Name: !Sub "${EnvironmentName}-PublicSubnets"

  PrivateSubnets:
    Value: !Join [",", [!Ref PrivateSubnetA]]
    Export:
      Name: !Sub "${EnvironmentName}-PrivateSubnets"

  ECSClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${EnvironmentName}-ECSClusterName"

  ECSTaskExecutionRoleArn:
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: !Sub "${EnvironmentName}-ECSTaskExecutionRoleArn"

  DefaultServiceSecurityGroupId:
    Value: !Ref DefaultServiceSecurityGroup
    Export:
      Name: !Sub "${EnvironmentName}-DefaultServiceSG"