AWSTemplateFormatVersion: "2010-09-09"
Description: Create the S3 bucket used for Envoy dynamic config.

Parameters:
  S3BucketName:
    Type: String
    Default: envoy-file-config
  SqsQueueName:
    Type: String
    Default: envoy-config-events

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt SqsQueue.Arn

  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref SqsQueueName

  SqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SqsQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt SqsQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub "arn:aws:s3:::${S3BucketName}"

Outputs:
  BucketName:
    Value: !Ref S3BucketName
  QueueName:
    Value: !Ref SqsQueueName
